### ISSUE TITLE
error when I receive the connections

### ISSUE THREAD

**Issue by progressify** [tobadia/petGPS#1]
Hi
Thanks for sharing with the community your work.
I have cloned your repo, and I have created a key for maps API.

But when I receive an incoming connection I receive this error:

```
127.0.0.1:41748 has connected.
[ 127.0.0.1 ] IN Hex : 474554202f20485454502f312e310d0a486f73743a206c6f63616c686f73743a393939390d0a557365722d4167656e743a204d6f7a696c6c612f352e3020285831313b205562756e74753b204c696e757820693638363b2072763a32342e3029204765636b6f2f32303130303130312046697265666f782f32342e300d0a4163636570743a206170706c69636174696f6e2f786d6c2c6170706c69636174696f6e2f7868746d6c2b786d6c2c746578742f68746d6c3b713d302e392c746578742f706c61696e3b713d302e382c696d6167652f706e672c2a2f2a3b713d302e350d0a4163636570742d456e636f64696e673a206964656e746974790d0a582d466f727761726465642d466f723a2038322e38342e31312e3137370d0a582d466f727761726465642d486f73743a207265706f72742e70726f67726573736966792e69740d0a582d466f727761726465642d5365727665723a207265706f72742e70726f67726573736966792e69740d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a0d0a (length in bytes = 394 )
[ 127.0.0.1 ] ERROR: socket was closed due to the following exception:
'20'
This thread is now closed.
```

What is 20 exception?

EDIT:
I have printed the stack trace:
```
Traceback (most recent call last):
  File "/home/progressify/Documenti/dev/petGPS/gps_tcp_server.py", line 93, in handle_client
    keepAlive = read_incoming_packet(client, packet)
  File "/home/progressify/Documenti/dev/petGPS/gps_tcp_server.py", line 131, in read_incoming_packet
    protocol_name = protocol_dict['protocol'][packet_list[1]]
KeyError: '20'

```

**Comment by tobadia** [comment]
Hi,
The packet sent is HUGE. Any hint as to what device you're using? This is likely a protocol different from the one I'm handling here. Packets I receive through my device are never that long, 10-20 bytes maximum.

**Comment by progressify** [comment]
Hi
I have buyed the zx303 from alibaba and the document that I have received from the seller is the same there is in your folder resources.
:O

**Comment by tobadia** [comment]
OK so there's definitely something off with what you are capturing. I'd bet it's a networking error somewhere: did you configure the ZX303 to send its data towards your public IP adress and are you listening on the proper port ?
It's definitely not normal that your _client_ has 127.0.0.1 as public address.

There are obviously other bugs in that DIY server (some hard to adress with that ugly and incomplete documentation) but first you'd have to make sure it's actually the device connecting, and not some other random packets from your own machine.

**Comment by progressify** [comment]
The 127.0.0.1 I think is because I have sent to the zx303 this command:
DOMAIN#subdomain.progressify.it#443#
And I have apache in proxypass to the tcp server

**Comment by tobadia** [comment]
OK, weird. What's transmitted is definitely altered. Any chance you can see the raw packets in proxypass ? What's forwarded is definitely not coming from the tracker, but was altered somewhere.

**Comment by progressify** [comment]
Ok, now I try to open the port and insert in domain command the IP and port directly, without apache in the middle

**Comment by progressify** [comment]
apache was always the problem, hahahahaha
thanks for the help! Now work perfectly.

I have the last question for you
sometimes in the console, I see this error, you know what is the problem?

```
[ 37.160.82.216 ] ERROR: socket was closed due to the following exception:

Traceback (most recent call last):
  File "/home/progressify/Documenti/dev/petGPS/myvenv/lib/python3.6/site-packages/googlemaps/client.py", line 258, in _request
    result = extract_body(response)
  File "/home/progressify/Documenti/dev/petGPS/myvenv/lib/python3.6/site-packages/googlemaps/geolocation.py", line 40, in _geolocation_extract
    raise exceptions._OverQueryLimit(response.status_code, error)
googlemaps.exceptions._OverQueryLimit: 403 (accessNotConfigured)
```

**Comment by progressify** [comment]
Found!
For some reason send 2 times same request and give 403 error the maps API. 

https://developers.google.com/maps/premium/previous-licenses/articles/usage-limits

**Comment by progressify** [comment]
Pull requests are accepted?

**Comment by tobadia** [comment]
Sure thing, would love to see improvements!

Apologies for not getting back in touch earlier. The exception will be thrown pretty much everytime the main loop is broken because of "anything unexpected". It will not be very informative most of the time, unfortunately, so I'll go back into the logs at that time and try and figure out what happened.

Among other things that need to be fixed and documented: it happens very often that the tracker apprently sends a position with lat/long = 0.0. This seems to be triggered after a "status" packet that is answered by my server, but likely in the wrong way. Unfortunately, documentation is.......... ugly (who said total shit ?)

**Comment by progressify** [comment]
Hi, I have forked your repo and now I think I will reorganize all your code in a class for use this in a Django project.
This is the URL of my repo: https://github.com/progressify/petGPS
If you agree, I can PR on your repo the class reorganization and in my repo, I create the app installable in Django.

**Comment by tobadia** [comment]
Hey,
Sure thing for the PR. Class-ifying that was actually on my to-do list for 'when I have enough time to do actual Python again'... and I've been rather busy at work and with other personal issues unfortunately. I do ultimately plan to take time to re-work this, bit I'll have to postpone for a bit.

I have branched my current dev into a 'warehouse' branch, just to archive this version. Feel free to send the PR!
