### ISSUE TITLE
Gps functions

### ISSUE THREAD

**Issue by eried** [tobadia/petGPS#3]
Hey! can you help me with few questions about this device?:

1) With this cheap modules do you have to interact with the button? Or they start powered "on"? 
2) Do they support 3G?
3) that 1-2 MB daily data you said was using what rate? Does the device automatically saves data when there is no movement?

Thanks!

**Comment by progressify** [comment]
1. You must to put in the tray the sim card, power on the device, configure the connection apn parameters with the SMS command and after this operation the device start to work 
2. If I remember good it is only 2g
3. I don't know

**Comment by progressify** [comment]
No, you must click the power button for 2 sec
It is all documented in the manual

**Comment by eried** [comment]
Gotcha, that sucks! I saw the documentation but you know how innacurate it is :)

**Comment by tobadia** [comment]
Hey !
A bit late to the party but nevertheless. I've somehow put this on an overdue standby ad plan to get back to it "when I have time".
Re you questions:
1. You have to interact with the module. There's a tiny button inside, that gets pushed by a (fragile) plastic bit that's inside the casing (in theory, pressing the outer casing makes that bit move, and it presses the actual button). If you're clumsy like I am, you may have to remove the plastic cache and press the button with a paperclip. Long press to power on/off, short press for some random shit (e.g. send SOS signal or whatever). Definitely not used for this sort of DIY project though, just going on/off.

2. The devices I mentioned in the (unfinished) ReadMe were 2G only. This is enough in France, for now, but can prove more tricky in other countries. There may be some new similar devies that can handle 3G, but I didn't look for it. What's sure is that ~1 year ago I couldn't find something that had "more or less" documented protocol + 3G support + small enough to fit on a pet.

3. When I said daily rate, that meant "suited to my cat, living its life with a pet door, so could go out or just chill at home". This kind of device is supposed to go to sleep when it's not detecting movement (accelerometer?), which is what i osberved when laying it on a table for a while. It also wakes up when there's movement. So, no, it should not be saving much data when not in movement after a while. This can probably be set by sending it SMS commands... but a full list of command isn't easy to find.

Any PR or suggestion, let me know. I also put together a RShiny UI to visualize the logs, but it's all messy for now, so I haven't pushed it yet to Github. Again... "someday" :)

**Comment by flywire** [comment]
Will GPS logging to SD-Card work without SIM?

**Comment by tobadia** [comment]
I honestly don't know what that device does when no Sim card is inserted. Since it's a client/server thing, I doubt it would work. At least not with my (old and probably outdated) framework.
