### ISSUE TITLE
Problem with googlemaps API

### ISSUE THREAD

**Issue by acdcjavier** [tobadia/petGPS#5]
First of all, thank you very much for your project, it is quite interesting how you decrypted the data sent to the server.

Of course, I have a problem regarding the googlemaps API.
I am running this script on a raspberry, even though I had some misconceptions regarding phyton to run the script and in addition to getting an API from google, I was finally able to start the server.

The problem is that the script, at the moment of giving the coordinates, indicates an error that does not appear:

```
Decoding location-based data using Google Maps Geolocation API ...
Google Maps Geolocation API queried with: {'wifi': [{'macAddress':' e4: ab: 89: 59: 68: 30 ',' signalStrength ': -28}, {' macAddress': 'e4: ab: 89: 59: 68: 00 ',' signalStrength ': -28}, {' macAddress ':' c6: d4: a1: 90: 23: ef ',' signalStrength ': -38}, {' macAddress ':' b0: b2: 8f: 42: ba: 3b ',' signalStrength ': -54}, {' macAddress ':' b0: b2: 8f: 42: b1: 2b ',' signalStrength ': -54}, {' macAddress ':' b2: 68: e6: 62: 95: 4f ',' signalStrength ': -57}, {' macAddress ': '60: 08: 10: 0f: 1b: d4', 'signalStrength': -60 }, {'macAddress': 'c0: 25: e9: 64: 2e: 2c', 'signalStrength': -73}], 'gsm-cells': [{'locationAreaCode': 29721, 'cellId': 9038, 'signalStrength': -90}, {'locationAreaCode': 29721, 'cellId': 8456, 'signalStrength': -100}, {'locationAreaCode': 29721, 'cellId': 21511, 'signalStrength': -100}, {'locationAreaCode': 29721, 'cellId': 8454, 'signalStrength': -100}], 'gsm-carrier': {'n_gsm_cells': 4,' MCC ': 730,' MNC ': 2},' gps ': {}}
[191.125.49.87] ERROR: socket was closed due to the following exception:

This thread is now closed
```

Do you ahve any idea how to solve that? or is it is okay?

**Comment by tobadia** [comment]
Hey @acdcjavier . This is a bit puzzling but there seems to be heaps of whitespaces that shouldn't be in the query, as well as quotes that are sometimes there, sometimes not.
I haven't been digging into that code recently but didn't have issue with querying the GMaps API.
This could be an issue with your version of Python (which one is running on you RPii ?)... or something system-dependant ? I'll try and re-run the server in the upcomign days on my end, see if things still run smooth or not.

Thanks

**Comment by acdcjavier** [comment]
> Hey @acdcjavier . This is a bit puzzling but there seems to be heaps of whitespaces that shouldn't be in the query, as well as quotes that are sometimes there, sometimes not.
> I haven't been digging into that code recently but didn't have issue with querying the GMaps API.
> This could be an issue with your version of Python (which one is running on you RPii ?)... or something system-dependant ? I'll try and re-run the server in the upcomign days on my end, see if things still run smooth or not.
> 
> Thanks

Hello, thanks for your reply, yes I'm using Rasbperry Pi 4 and using the latest Phyton 3 avaiable in RP4

**Comment by tobadia** [comment]
Confirmed, this is indeed an issue with the query contianing whitespaces everywhere 👍 
```
positionDict = {'wifi': [{'macAddress':' e4: ab: 89: 59: 68: 30 ',' signalStrength ': -28}, {' macAddress': 'e4: ab: 89: 59: 68: 00 ',' signalStrength ': -28}, {' macAddress ':' c6: d4: a1: 90: 23: ef ',' signalStrength ': -38}, {' macAddress ':' b0: b2: 8f: 42: ba: 3b ',' signalStrength ': -54}, {' macAddress ':' b0: b2: 8f: 42: b1: 2b ',' signalStrength ': -54}, {' macAddress ':' b2: 68: e6: 62: 95: 4f ',' signalStrength ': -57}, {' macAddress ': '60: 08: 10: 0f: 1b: d4', 'signalStrength': -60 }, {'macAddress': 'c0: 25: e9: 64: 2e: 2c', 'signalStrength': -73}], 'gsm-cells': [{'locationAreaCode': 29721, 'cellId': 9038, 'signalStrength': -90}, {'locationAreaCode': 29721, 'cellId': 8456, 'signalStrength': -100}, {'locationAreaCode': 29721, 'cellId': 21511, 'signalStrength': -100}, {'locationAreaCode': 29721, 'cellId': 8454, 'signalStrength': -100}], 'gsm-carrier': {'n_gsm_cells': 4,' MCC ': 730,' MNC ': 2},' gps ': {}}

# Load libraries
from dotenv import load_dotenv
from socket import AF_INET, socket, SOCK_STREAM
from threading import Thread
from datetime import datetime
from dateutil import tz
import googlemaps
import math
import os

# Initialize Gmaps API
load_dotenv()
GMAPS_API_KEY = os.getenv('GMAPS_API_KEY')
gmaps = googlemaps.Client(key=GMAPS_API_KEY)

# Try and query the API, it fails because of the whitespaces everywhere
gmaps.geolocate(home_mobile_country_code=positionDict['gsm-carrier']['MCC'], 
        home_mobile_network_code=positionDict['gsm-carrier']['MCC'], 
        radio_type='gsm', 
        carrier='Free', 
        consider_ip='true', 
        cell_towers=positionDict['gsm-cells'], 
        wifi_access_points=positionDict['wifi'])
```

The (first) error is : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'MCC'
```
Because there's no `'MCC'` key in he dictionary, but rather a `' MCC '`. Though there's no reason for these whitespaces to be included as the keys of these dictionaries are hardcoded (e.g. line 369 for this specific one).

I'd definitely look for somethign system-dependant. Could you try and check in your sources if these whtespaces appear ?

**Comment by acdcjavier** [comment]
I'm a bit newie about operating some source, 

I've tested too recently in Ubuntu 20 using antoher computer and the problem is the same, got whitesapce and the thread is closed.

PD: also you need to create a "log" folder in your repository code

**Comment by tobadia** [comment]
I've tried the sources on my own laptop and don't have these whitespaces anywhere. Are you sure you didn't alter the content of the sources by looking at them ?
Best thing would be to clone the git repo again and see what happens.

**Comment by acdcjavier** [comment]
> I've tried the sources on my own laptop and don't have these whitespaces anywhere. Are you sure you didn't alter the content of the sources by looking at them ?
> Best thing would be to clone the git repo again and see what happens.
> 
> I'm running Python 3.8.5 but this should not be an issue at all.
> 
> Btw, cheers for pointing out the missing "logs" folder. Added it again.

Hello
Recenlty i've downloaded again your source but the problem still persist, it keeps whitespaces :/
Im using python 3.8
pip3 20.0.2

**Comment by acdcjavier** [comment]
Ok I've uplaoded the code
https://drive.google.com/file/d/1e256_YInKNHZs8MiHMFnhmKTXXlQVgfN/view?usp=sharing

I only edited the code when I insert the Google maps API key

**Comment by tobadia** [comment]
Extremely weird. There's no whitespace in this one. I have no clue as to where this happens. As an example, here's how it looks in my console for a Gmaps API query :
```
The current packet is for protocol: wifi_offline_positioning which has method: datetime_response
[ 37.166.201.201 ] POSITION/WIFI : BSSID = f4:e1:1e:06:d7:91 ; RSSI = -90
[ 37.166.201.201 ] POSITION/WIFI : BSSID = 84:a1:d1:2e:b4:50 ; RSSI = -91
[ 37.166.201.201 ] POSITION/WIFI : BSSID = d4:f8:29:42:e0:20 ; RSSI = -91
[ 37.166.201.201 ] POSITION/WIFI : BSSID = d4:f8:29:42:e0:21 ; RSSI = -91
[ 37.166.201.201 ] POSITION/WIFI : BSSID = f4:6b:ef:66:e4:d6 ; RSSI = -89
[ 37.166.201.201 ] POSITION/WIFI : BSSID = e8:be:81:99:80:20 ; RSSI = -75
[ 37.166.201.201 ] POSITION/WIFI : BSSID = b8:26:6c:ff:4b:de ; RSSI = -80
[ 37.166.201.201 ] POSITION/WIFI : BSSID = 30:7c:b2:58:14:1f ; RSSI = -74
[ 37.166.201.201 ] POSITION/LBS : LAC = 6101 ; CellID = 64352 ; MCISS = -70
[ 37.166.201.201 ] POSITION/LBS : LAC = 6101 ; CellID = 64353 ; MCISS = -70
[ 37.166.201.201 ] POSITION/LBS : LAC = 6101 ; CellID = 46219 ; MCISS = -90
Decoding location-based data using Google Maps Geolocation API...
Google Maps Geolocation API queried with: {'wifi': [{'macAddress': 'f4:e1:1e:06:d7:91', 'signalStrength': -90}, {'macAddress': '84:a1:d1:2e:b4:50', 'signalStrength': -91}, {'macAddress': 'd4:f8:29:42:e0:20', 'signalStrength': -91}, {'macAddress': 'd4:f8:29:42:e0:21', 'signalStrength': -91}, {'macAddress': 'f4:6b:ef:66:e4:d6', 'signalStrength': -89}, {'macAddress': 'e8:be:81:99:80:20', 'signalStrength': -75}, {'macAddress': 'b8:26:6c:ff:4b:de', 'signalStrength': -80}, {'macAddress': '30:7c:b2:58:14:1f', 'signalStrength': -74}], 'gsm-cells': [{'locationAreaCode': 6101, 'cellId': 64352, 'signalStrength': -70}, {'locationAreaCode': 6101, 'cellId': 64353, 'signalStrength': -70}, {'locationAreaCode': 6101, 'cellId': 46219, 'signalStrength': -90}], 'gsm-carrier': {'n_gsm_cells': 3, 'MCC': 208, 'MNC': 1}, 'gps': {}}
Google Maps Geolocation API returned: {'location': {'lat': 48.833980499999996, 'lng': 2.355108}, 'accuracy': 20}
```

**Comment by tobadia** [comment]
I've just noticed that you've edited the source code to include your Gmaps API key. As it's strictly private, I suggest you revoke that key and generate a new one. Otherwise, anyone can be able to query Gmaps API with your key... imagine if hundreds of thousands of queries were to to run, you'd end up with bills to pay.

I thought I had included that in the README but it's not. The Gmaps API key should be in a "dotenv" file, I'll edit the instructions to help you include your key safely.

**Comment by acdcjavier** [comment]
> I've just noticed that you've edited the source code to include your Gmaps API key. As it's strictly private, I suggest you revoke that key and generate a new one. Otherwise, anyone can be able to query Gmaps API with your key... imagine if hundreds of thousands of queries were to to run, you'd end up with bills to pay.
> 
> I thought I had included that in the README but it's not. The Gmaps API key should be in a "dotenv" file, I'll edit the instructions to help you include your key safely.
> 
> At the same time, I think all your issues come down to that edit. I'm fairly sure you've introduced a silent encoding bug that causes these whitespaces to appear.
> 
> edit: updated. see : https://github.com/tobadia/petGPS#google-maps-api-key-with-dotenv
> Try and download the repository again, and don't open/edit the `gps_tcp_server.py` file. Juste create your own `.env` file as instructed with your (new) Gmaps API key. Hopefully the issue will go away... 🤞

Thanks so much, I've download again the source also I edited the .env file with a new API key but still the problem with withespace

Maybe pip3 modules problem?
I have those modules installed:

Package                Version             
---------------------- --------------------
apturl                 0.5.2               
asn1crypto             0.24.0              
beautifulsoup4         4.8.2               
blinker                1.4                 
Brlapi                 0.7.0               
certifi                2019.11.28          
chardet                3.0.4               
Click                  7.0                 
colorama               0.4.3               
command-not-found      0.3                 
cryptography           2.8                 
cupshelpers            1.0                 
cycler                 0.10.0              
dbus-python            1.2.16              
defer                  1.0.6               
distro                 1.4.0               
distro-info            0.23ubuntu1         
entrypoints            0.3                 
googlemaps             4.4.2               
html5lib               1.0.1               
httplib2               0.14.0              
idna                   2.8                 
keyring                18.0.1              
kiwisolver             1.0.1               
language-selector      0.1                 
launchpadlib           1.10.13             
lazr.restfulclient     0.14.2              
lazr.uri               1.0.3               
louis                  3.12.0              
lxml                   4.5.0               
macaroonbakery         1.3.1               
matplotlib             3.1.2               
netifaces              0.10.4              
numpy                  1.17.4              
oauthlib               3.1.0               
olefile                0.46                
pexpect                4.6.0               
Pillow                 7.0.0               
pip                    20.0.2              
protobuf               3.6.1               
pycairo                1.16.2              
pycups                 1.9.73              
PyGObject              3.36.0              
PyJWT                  1.7.1               
pymacaroons            0.13.0              
PyNaCl                 1.3.0               
pyparsing              2.4.6               
PyQt5                  5.14.1              
pyRFC3339              1.1                 
pyserial               3.4                 
python-apt             2.0.0+ubuntu0.20.4.1
python-dateutil        2.7.3               
python-debian          0.1.36ubuntu1       
python-dotenv          0.9.1               
pytz                   2019.3              
pyusb                  1.0.2               
pyxdg                  0.26                
PyYAML                 5.3.1               
reportlab              3.5.34              
requests               2.22.0              
requests-unixsocket    0.2.0               
SecretStorage          2.3.1               
setuptools             45.2.0              
simplejson             3.16.0              
sip                    4.19.21             
six                    1.14.0              
soupsieve              1.9.5               
ssh-import-id          5.10                
system-service         0.3                 
systemd-python         234                 
ubuntu-advantage-tools 20.3                
ubuntu-drivers-common  0.0.0               
ufw                    0.36                
unattended-upgrades    0.1                 
urllib3                1.25.8              
wadllib                1.3.3               
webencodings           0.5.1               
wheel                  0.34.2              
xkit                   0.0.0

**Comment by tobadia** [comment]
Ultra weird. I'll look into updating the pipenv version so you can try a packaged version of the script with a virtual environment. Should rule out issues with dependencies... I'll let you know once this is done.

**Comment by tobadia** [comment]
Pipenv was updated. Can you:
1) Install pipenv (see https://pypi.org/project/pipenv/ for correct one-liner depending on your dustrib)
2) Re-clone my repository to be sure you've got the latest, unaltered sources
3) in the directory cloned from my github, run
```pipenv run python gps_tcp_server.py```

Cheers

**Comment by acdcjavier** [comment]
> Pipenv was updated. Can you:
> 
>     1. Install pipenv (see https://pypi.org/project/pipenv/ for correct one-liner depending on your dustrib)
> 
>     2. Re-clone my repository to be sure you've got the latest, unaltered sources
> 
>     3. in the directory cloned from my github, run
>        `pipenv run python gps_tcp_server.py`
> 
> 
> Cheers

Hello
Recenlty i'v tested again.
It was very difficult for eject pipenv because i had some prolem with the pip modules that pipenv didn't recognize installed modules and I had to use pipenv shell and install each modules again
But I can see that the problem maybe is your code and not other.

```
javier@MBServices-Javier:~/petGPS$ pipenv run python gps_tcp_server.py
Loading .env environment variables…
Waiting for connection...
191.126.148.233:26048 has connected.
[ 191.126.148.233 ] IN Hex : 78780d0103593390759182184d0d0a (length in bytes = 15 )
The current packet is for protocol: login which has method: login
Detected IMEI : 359339075918218 and Sw v. : 77
[ 191.126.148.233 ] OUT Hex : 787801010D0A (length in bytes = 6 )
[ 191.126.148.233 ] IN Hex : 787801570d0a (length in bytes = 6 )
The current packet is for protocol: setup which has method: setup
[ 191.126.148.233 ] OUT Hex : 78781E570300310000000000000000000000000000000000000000000000003B3B0D0A (length in bytes = 35 )
[ 191.126.148.233 ] IN Hex : 78780713444d0819480d0a (length in bytes = 11 )
The current packet is for protocol: status which has method: 
[ 191.126.148.233 ] STATUS : Battery = 68 ; Sw v. = 77 ; Status upload interval = 8 ; Signal strength = 25
[ 191.126.148.233 ] IN Hex : 78780769201016160325e4ab8959680026b268e662954f37ccd4a1b5b02037b0b28f42b12b3db0b28f42ba3b406008100f1bd441c025e9642e2c4c0602da02741921085a7419234e5a741921c0647419210764741921c264741a22fb6e000d0a (length in bytes = 96 )
The current packet is for protocol: wifi_positioning which has method: datetime_position_response
[ 191.126.148.233 ] POSITION/WIFI : BSSID = e4:ab:89:59:68:00 ; RSSI = -38
[ 191.126.148.233 ] POSITION/WIFI : BSSID = b2:68:e6:62:95:4f ; RSSI = -55
[ 191.126.148.233 ] POSITION/WIFI : BSSID = cc:d4:a1:b5:b0:20 ; RSSI = -55
[ 191.126.148.233 ] POSITION/WIFI : BSSID = b0:b2:8f:42:b1:2b ; RSSI = -61
[ 191.126.148.233 ] POSITION/WIFI : BSSID = b0:b2:8f:42:ba:3b ; RSSI = -64
[ 191.126.148.233 ] POSITION/WIFI : BSSID = 60:08:10:0f:1b:d4 ; RSSI = -65
[ 191.126.148.233 ] POSITION/WIFI : BSSID = c0:25:e9:64:2e:2c ; RSSI = -76
[ 191.126.148.233 ] POSITION/LBS : LAC = 29721 ; CellID = 8456 ; MCISS = -90
[ 191.126.148.233 ] POSITION/LBS : LAC = 29721 ; CellID = 9038 ; MCISS = -90
[ 191.126.148.233 ] POSITION/LBS : LAC = 29721 ; CellID = 8640 ; MCISS = -100
[ 191.126.148.233 ] POSITION/LBS : LAC = 29721 ; CellID = 8455 ; MCISS = -100
[ 191.126.148.233 ] POSITION/LBS : LAC = 29721 ; CellID = 8642 ; MCISS = -100
[ 191.126.148.233 ] POSITION/LBS : LAC = 29722 ; CellID = 8955 ; MCISS = -110
Decoding location-based data using Google Maps Geolocation API...
Google Maps Geolocation API queried with: {'wifi': [{'macAddress': 'e4:ab:89:59:68:00', 'signalStrength': -38}, {'macAddress': 'b2:68:e6:62:95:4f', 'signalStrength': -55}, {'macAddress': 'cc:d4:a1:b5:b0:20', 'signalStrength': -55}, {'macAddress': 'b0:b2:8f:42:b1:2b', 'signalStrength': -61}, {'macAddress': 'b0:b2:8f:42:ba:3b', 'signalStrength': -64}, {'macAddress': '60:08:10:0f:1b:d4', 'signalStrength': -65}, {'macAddress': 'c0:25:e9:64:2e:2c', 'signalStrength': -76}], 'gsm-cells': [{'locationAreaCode': 29721, 'cellId': 8456, 'signalStrength': -90}, {'locationAreaCode': 29721, 'cellId': 9038, 'signalStrength': -90}, {'locationAreaCode': 29721, 'cellId': 8640, 'signalStrength': -100}, {'locationAreaCode': 29721, 'cellId': 8455, 'signalStrength': -100}, {'locationAreaCode': 29721, 'cellId': 8642, 'signalStrength': -100}, {'locationAreaCode': 29722, 'cellId': 8955, 'signalStrength': -110}], 'gsm-carrier': {'n_gsm_cells': 6, 'MCC': 730, 'MNC': 2}, 'gps': {}}
[ 191.126.148.233 ] ERROR: socket was closed due to the following exception:

This thread is now closed.
```

**Comment by tobadia** [comment]
Well this time it's not an issue about whitespaces. They are gone from this string. In fact, your query works very fine here:

```
positionDict = {'wifi': [{'macAddress': 'e4:ab:89:59:68:00', 'signalStrength': -38}, {'macAddress': 'b2:68:e6:62:95:4f', 'signalStrength': -55}, {'macAddress': 'cc:d4:a1:b5:b0:20', 'signalStrength': -55}, {'macAddress': 'b0:b2:8f:42:b1:2b', 'signalStrength': -61}, {'macAddress': 'b0:b2:8f:42:ba:3b', 'signalStrength': -64}, {'macAddress': '60:08:10:0f:1b:d4', 'signalStrength': -65}, {'macAddress': 'c0:25:e9:64:2e:2c', 'signalStrength': -76}], 'gsm-cells': [{'locationAreaCode': 29721, 'cellId': 8456, 'signalStrength': -90}, {'locationAreaCode': 29721, 'cellId': 9038, 'signalStrength': -90}, {'locationAreaCode': 29721, 'cellId': 8640, 'signalStrength': -100}, {'locationAreaCode': 29721, 'cellId': 8455, 'signalStrength': -100}, {'locationAreaCode': 29721, 'cellId': 8642, 'signalStrength': -100}, {'locationAreaCode': 29722, 'cellId': 8955, 'signalStrength': -110}], 'gsm-carrier': {'n_gsm_cells': 6, 'MCC': 730, 'MNC': 2}, 'gps': {}}

# Load libraries
from dotenv import load_dotenv
from socket import AF_INET, socket, SOCK_STREAM
from threading import Thread
from datetime import datetime
from dateutil import tz
import googlemaps
import math
import os

# Initialize Gmaps API
load_dotenv()
GMAPS_API_KEY = os.getenv('GMAPS_API_KEY')
gmaps = googlemaps.Client(key=GMAPS_API_KEY)

# Try and query the API, it fails because of the whitespaces everywhere
gmaps.geolocate(home_mobile_country_code=positionDict['gsm-carrier']['MCC'], 
        home_mobile_network_code=positionDict['gsm-carrier']['MCC'], 
        radio_type='gsm', 
        carrier='Free', 
        consider_ip='true', 
        cell_towers=positionDict['gsm-cells'], 
        wifi_access_points=positionDict['wifi'])
```

Returns
```
{'location': {'lat': -33.4373092, 'lng': -70.6323726}, 'accuracy': 28}
```

(btw, you may want me to edit out the locations and redact the data that was used to find that point. If you want me to edit, just let me know in a subsequent comment)

At this stage, I would look for an issue with your Gmaps API accesses. What do you see on the Google API console (here: https://console.cloud.google.com/google/maps-apis/credentials) ? Could there be restrictions or reasons why your API call would fail ?

To the very least, your local Python environment introduces the whitespaces that were there before. So, you have at least two distinct issues.
